services:
  #access: docker exec -it mysql_db_new mysql -u root -p"secureRootPass123"
  db:
    image: mysql:latest
    container_name: mysql_db_new
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app-network

  # spring-app:
  #   build:
  #     context: ./spring-app
  #     dockerfile: Dockerfile
  #   container_name: spring_app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
  #     SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
  #     SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
  #   depends_on:
  #    - db
  #   networks:
  #     - app-network
  app:
    build:
      context: ./spring-app
      dockerfile: Dockerfile
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network


networks:
  app-network:
    driver: bridge


  

